# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data.rpc_service.msg_pb2 as msg__pb2


class SerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.rec = channel.unary_unary(
                '/SerService/rec',
                request_serializer=msg__pb2.inMsg.SerializeToString,
                response_deserializer=msg__pb2.outMsg.FromString,
                )


class SerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def rec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'rec': grpc.unary_unary_rpc_method_handler(
                    servicer.rec,
                    request_deserializer=msg__pb2.inMsg.FromString,
                    response_serializer=msg__pb2.outMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def rec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SerService/rec',
            msg__pb2.inMsg.SerializeToString,
            msg__pb2.outMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
