# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tmsg.proto\")\n\x05inMsg\x12\x13\n\x0bphonenumber\x18\x01 \x01(\t\x12\x0b\n\x03num\x18\x02 \x01(\x05\"\x15\n\x06outMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t2$\n\nSerService\x12\x16\n\x03rec\x12\x06.inMsg\x1a\x07.outMsgb\x06proto3'
)



_INMSG = _descriptor.Descriptor(
  name='inMsg',
  full_name='inMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='phonenumber', full_name='inMsg.phonenumber', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num', full_name='inMsg.num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=54,
)


_OUTMSG = _descriptor.Descriptor(
  name='outMsg',
  full_name='outMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='outMsg.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['inMsg'] = _INMSG
DESCRIPTOR.message_types_by_name['outMsg'] = _OUTMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

inMsg = _reflection.GeneratedProtocolMessageType('inMsg', (_message.Message,), {
  'DESCRIPTOR' : _INMSG,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:inMsg)
  })
_sym_db.RegisterMessage(inMsg)

outMsg = _reflection.GeneratedProtocolMessageType('outMsg', (_message.Message,), {
  'DESCRIPTOR' : _OUTMSG,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:outMsg)
  })
_sym_db.RegisterMessage(outMsg)



_SERSERVICE = _descriptor.ServiceDescriptor(
  name='SerService',
  full_name='SerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=79,
  serialized_end=115,
  methods=[
  _descriptor.MethodDescriptor(
    name='rec',
    full_name='SerService.rec',
    index=0,
    containing_service=None,
    input_type=_INMSG,
    output_type=_OUTMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERSERVICE)

DESCRIPTOR.services_by_name['SerService'] = _SERSERVICE

# @@protoc_insertion_point(module_scope)
